language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - "pip install -r test-requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"

script:
  - nosetests -sv --with-doctest --nologcapture --with-coverage --cover-tests

after_success:
  - coveralls
