language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - "pip install -r test-requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"

script:
  # this should get options from setup.cfg
  - nosetests

after_success:
  - coveralls
